### ISSUE TITLE
Build broken on Windows

### ISSUE THREAD

**Issue by knutwannheden** [wmay/dwnominate#14]
It seems like the commit https://github.com/wmay/dwnominate/commit/77757575d0640778b351d5de4b549f893f8cc89f broke the Windows build. The commit just before that still compiles fine on my machine running Windows 10:

```console
> R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.4                         
year           2021                        
month          02                          
day            15                          
svn rev        80002                       
language       R                           
version.string R version 4.0.4 (2021-02-15)
nickname       Lost Library Book           
```

Here is the errors I get when I try to install `dwnominate`:

```console
> remotes::install_github('wmay/dwnominate', '77757575d0640778b351d5de4b549f893f8cc89f')

...
   /mingw64/bin/gcc -shared -s -static-libgcc -o dwnominate.dll tmp.def dwnom.o -LC:/PROGRA~1/R/R-40~1.4/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-40~1.4/bin/x64 -lRblas -lgfortran -lm -lquadmath -lgfortran -lm -lquadmath -LC:/PROGRA~1/R/R-40~1.4/bin/x64 -lR
   C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: dwnom.o:dwnom.f:(.text+0x952d): undefined reference to `sgesvd_'
   C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: dwnom.o:dwnom.f:(.text+0x9610): undefined reference to `sgesvd_'
   collect2.exe: error: ld returned 1 exit status
   no DLL was created
   ERROR: compilation failed for package 'dwnominate'
```

**Comment by wmay** [comment]
After that commit you need BLAS and LAPACK to compile it. They should be included in [Rtools](https://cran.r-project.org/bin/windows/Rtools/). Let me know if that helps.

**Comment by knutwannheden** [comment]
I do have Rtools 4.0 and R.Project 4.0.4 installed. BLAS AND LAPACK appear to be part of R.Project and available as Rblas.dll and Rlapack.dll. And I assume the older versions of this library also use LAPACK and / or BLAS. Since I am able to install the oder versions just fine, I assume my setup is basically fine. I suspect this is some platform specific issue. I don't have much experience with R, so I am afraid I won't be able to help much. Possibly someone else could try to confirm these problems on Windows?

**Comment by wmay** [comment]
Not quite. You need the BLAS and LAPACK development headers to do compiling. R itself only comes with the shared libraries (the dll's). That's why there's a separate Rtools package for compiling packages. And that's why gcc complains about `sgesvd`, which is a LAPACK function.

Older versions of this package didn't use LAPACK. They used IMSL and EISPACK code included in the fortran source file. I replaced it with LAPACK in this commit because the IMSL code is proprietary.

So this almost certainly suggests that Rtools somehow isn't set up correctly. Your compiler just needs to be pointed to the LAPACK development headers.

**Comment by knutwannheden** [comment]
My R on Windows does also have LAPACK and BLAS C header files. They are under `include/R_ext` and you can inspect them here: https://svn.r-project.org/R/trunk/src/include/R_ext/Lapack.h and https://svn.r-project.org/R/trunk/src/include/R_ext/BLAS.h.

I have no idea what the "R flavor" of these two libraries is or how it differs from the standard libraries. But I think I have my R and Rtools installed properly and suspect that only installing Rtools is not quite enough on Windows.

**Comment by wmay** [comment]
You're linking to the R source code, but if you install R on windows you would typically only have the binary. I'm not working on a windows machine at the moment but my understanding is that you won't end up with those files on your system. They may not be found by the compiler even if you do have the files.

The [Rtools source code](https://github.com/r-windows/rtools-packages) shows that it includes lapack, which is why I expect it to work.

But I also haven't used this new version of Rtools before, and I'm a bit confused about what they're doing. Let me try this out with my windows machine and get back to you.

**Comment by wmay** [comment]
Can you try following the Rtools instructions [here](https://github.com/r-windows/docs/blob/master/rtools40.md#readme)?

It looks like you would need to run something along the lines of:

```
pacman -S  mingw-w64-{i686,x86_64}-lapack
```

And that should provide the development headers for you.

**Comment by wmay** [comment]
Wow, I got that wrong-- the lapack headers really are installed with R. The issue seems to be that the functions I'm calling aren't included in R's lapack. I'll have to ask around on some mailing lists, because I actually don't know how to make this work right now.

**Comment by knutwannheden** [comment]
Thanks a lot for looking into this. If you figure out a way to solve this with using BLAS and LAPACK bundled with R, then great. Otherwise it would maybe be possible to publish a compiled package to CRAN to make it easier to use for Windows users.

**Comment by wmay** [comment]
Unfortunately it's not possible, because I literally can't compile it on windows right now (and putting the package on CRAN is not an option at the moment). After I get this sorted out though, if the compilation process is too complicated, I will definitely try to provide a binary version.

**Comment by knutwannheden** [comment]
I am happy to help you test, if that is of any help.

**Comment by wmay** [comment]
I think I've got it. Try running

```R
remotes::install_github('wmay/dwnominate', ref = 'lapack')
```

**Comment by knutwannheden** [comment]
Yes, indeed. Like this it now works!
