### ISSUE TITLE
Problem with polarity

### ISSUE THREAD

**Issue by OkeBahnsen** [wmay/dwnominate#18]
Hi,

I get the following error when using the dwnomiate()-command with my data:

> Error in if (new_legs[polarity[n], "c1"] < median(new_legs$c1, na.rm = TRUE)) { : 
>   missing value where TRUE/FALSE needed

I can also replicate this error with the nhsenate dataset, when I restrict nhsenate to the first four sessions:

dwnominate(nhsenate[1:4], polarity = c("Clifton Below", "Edward (Ned) Gordon"))

Note that both Clifton Below as well as Edward (Ned) Gordon are members of these four sessions. Also note that the code above strangely works for the first five sessions (i.e., for nhsenate[1:5]).

Thank you for your help!

**Comment by wmay** [comment]
So the way I have this set up, if you don't provide starting estimates, `dwnominate` calls `common_space` to get them. And by default `common_space` requires legislators to show up in at least 5 sessions in order to make scores. That's why using only 4 sessions of the New Hampshire data doesn't work. For less than 5 sessions, you'll have to provide the starting estimates.

The requirement for 5 sessions is also hard coded in `dwnominate`, so only the constant model works with fewer than 5 sessions.

I should improve the documentation and error messages around this.
